lib/binding/email_verification_binding.dart, lib/controller/create_account_controller.dart, lib/controller/email_verification_controller.dart, lib/controller/login_controller.dart, lib/controller/password_recovery_controller.dart, lib/controller/quiz_question_controller.dart, lib/controller/splash_controller.dart, lib/data/datasource/api_data_source.dart, lib/data/datasource/impl/ApiDataSourceImpl.dart, lib/data/repository/satar_repository_impl.dart, lib/data/response/verify_account_response.dart, lib/domain/entities/amount_currency.dart, lib/domain/repositories/sator_repository.dart, lib/translation/en.dart, lib/ui/page_widget/create_account_page.dart, lib/ui/page_widget/email_verification_page.dart, lib/ui/page_widget/forgot_password_page.dart, lib/ui/page_widget/forgot_password_reset.dart, lib/ui/page_widget/forgot_password_verification_page.dart, lib/ui/page_widget/login_page.dart, lib/ui/page_widget/quiz_question_page.dart
https://nftprojectsboosty.atlassian.net/browse/SAT-114 Display errors in modal window instead of current implementation
https://nftprojectsboosty.atlassian.net/browse/SAT-118 Remove next button on the quiz screen
https://nftprojectsboosty.atlassian.net/browse/SAT-122 Clean verification code if client gets error in response
https://nftprojectsboosty.atlassian.net/browse/SAT-123 Check if a user verified after each login
https://nftprojectsboosty.atlassian.net/browse/SAT-124 Add button to resend verification code
https://nftprojectsboosty.atlassian.net/browse/SAT-128 Change base API URL
=> Sat-nnn Small tasks

lib/controller/home_controller.dart, lib/data/datasource/api_data_source.dart, lib/data/datasource/impl/ApiDataSourceImpl.dart, lib/data/repository/satar_repository_impl.dart, lib/domain/repositories/sator_repository.dart, lib/ui/page_widget/home_page.dart
Change home: replace badges, challenges, nfts to show categories
=> Shows category

lib/controller/main_controller.dart, lib/controller/wallet_controller.dart, lib/data/datasource/api_data_source.dart, lib/data/datasource/impl/ApiDataSourceImpl.dart, lib/data/repository/satar_repository_impl.dart, lib/domain/repositories/sator_repository.dart, lib/ui/page_widget/email_verification_page.dart, lib/ui/page_widget/forgot_password_verification_page.dart, lib/ui/page_widget/main_page.dart, lib/ui/page_widget/wallet_page.dart
https://nftprojectsboosty.atlassian.net/browse/SAT-146
https://nftprojectsboosty.atlassian.net/browse/SAT-143
https://nftprojectsboosty.atlassian.net/browse/SAT-124
=> Wallet claim rewards, update wallets

lib/ui/page_widget/show_episodes_page.dart
https://nftprojectsboosty.atlassian.net/browse/SAT-247
=> SAT-247 Hide seasons navigation

lib/ui/page_widget/home_page.dart, lib/ui/page_widget/show_episodes_page.dart, lib/ui/page_widget/show_episodes_realm_page.dart, lib/ui/page_widget/shows_page.dart
https://nftprojectsboosty.atlassian.net/browse/SAT-250
=> SAT-250 Add shadow on show and episode blocks

lib/controller/main_controller.dart, lib/controller/wallet_controller.dart, lib/data/datasource/api_data_source.dart, lib/data/datasource/impl/ApiDataSourceImpl.dart, lib/data/datasource/impl/LocalDataSourceImpl.dart, lib/data/datasource/local_data_source.dart, lib/data/db_adapter/adapter_type_ids.dart, lib/data/db_adapter/transaction_adapter.dart, lib/data/model/transaction_model.dart, lib/data/repository/satar_repository_impl.dart, lib/domain/entities/transaction.dart, lib/domain/repositories/sator_repository.dart, lib/ui/page_widget/main_page.dart, lib/ui/page_widget/wallet_page.dart
https://nftprojectsboosty.atlassian.net/browse/SAT-186
=> Sat-186 Transactions storage

.gitignore, android/app/build.gradle, android/app/src/main/AndroidManifest.xml, lib/controller/show_episode_realm_controller.dart, lib/data/datasource/impl/ApiDataSourceImpl.dart, pubspec.lock
Reverts SatorNetwork/sator-flutter-client#83
=> Revert "Android release sign"

lib/binding/create_review_binding.dart, lib/controller/create_review_controller.dart, lib/controller/email_verification_controller.dart, lib/controller/password_recovery_controller.dart, lib/controller/show_detail_with_episodes_controller.dart, lib/controller/show_episode_realm_controller.dart, lib/controller/wallet_receive_controller.dart, lib/data/datasource/api_data_source.dart, lib/data/datasource/impl/ApiDataSourceImpl.dart, lib/data/repository/satar_repository_impl.dart, lib/data/request/write_review_request.dart, lib/domain/repositories/sator_repository.dart, lib/translation/en.dart, lib/ui/bottom_sheet_widget/rate_bottom_sheet.dart, lib/ui/dialog_widget/send_invite_dialog.dart, lib/ui/page_widget/chat_page.dart, lib/ui/page_widget/create_review_page.dart, lib/ui/page_widget/show_detail_with_episodes_page.dart, lib/ui/page_widget/show_episodes_realm_page.dart, lib/ui/widget/input_text_field.dart
https://nftprojectsboosty.atlassian.net/browse/SAT-402 Write review screen
https://nftprojectsboosty.atlassian.net/browse/SAT-398 Registration flow, Verification code -> add toast "Code was resent" if user tapping on Resend button
=> SAT-402 Write review

lib/controller/show_detail_with_episodes_controller.dart, lib/data/datasource/api_data_source.dart, lib/data/datasource/impl/ApiDataSourceImpl.dart, lib/data/model/show_detail_model.dart, lib/data/repository/satar_repository_impl.dart, lib/domain/entities/show_detail.dart, lib/domain/repositories/sator_repository.dart, lib/ui/page_widget/show_detail_with_episodes_page.dart
https://nftprojectsboosty.atlassian.net/browse/SAT-387 Implement claps functionality
=> Sat-387 Implement claps functionality

lib/controller/challenge_controller.dart, lib/controller/create_account_controller.dart, lib/controller/email_verification_controller.dart, lib/controller/login_controller.dart, lib/controller/password_recovery_controller.dart, lib/controller/quiz_controller.dart, lib/controller/show_detail_with_episodes_controller.dart, lib/controller/show_episode_realm_controller.dart, lib/controller/wallet_send_controller.dart, lib/controller/web_controller.dart, lib/controller/write_review_controller.dart, lib/data/model/challenge_model.dart, lib/domain/entities/challenge.dart, lib/domain/entities/episode_activation.dart, lib/translation/en.dart, lib/ui/page_widget/challenge_page.dart, lib/ui/page_widget/create_account_page.dart, lib/ui/page_widget/email_verification_page.dart, lib/ui/page_widget/forgot_password_verification_page.dart, lib/ui/page_widget/login_page.dart, lib/ui/page_widget/quiz_result_page.dart, lib/ui/page_widget/show_episodes_realm_page.dart, lib/ui/page_widget/wallet_send_page.dart, lib/ui/page_widget/write_review_page.dart, lib/ui/widget/elevated_gradient_button.dart
https://nftprojectsboosty.atlassian.net/browse/SAT-375 Terms of use -> link calls "Terms of SERVICE
https://nftprojectsboosty.atlassian.net/browse/SAT-407 Refresh rate after review added
https://nftprojectsboosty.atlassian.net/browse/SAT-408 Long username overlapping in reviews
https://nftprojectsboosty.atlassian.net/browse/SAT-381 Proceed to Episode screen in case if no more attempts left for Quiz
https://nftprojectsboosty.atlassian.net/browse/SAT-419 Deactivate claps after user reach limit
https://nftprojectsboosty.atlassian.net/browse/SAT-418 Deactivate button 'resend code' and have 1 minute delay countdown
https://nftprojectsboosty.atlassian.net/browse/SAT-217 Crash with Password recovery flow
Add 'In progress' state with progress indicator to main app button
=> Progress button

lib/data/model/challenge_model.dart, lib/domain/entities/challenge.dart, lib/translation/en.dart, lib/ui/page_widget/challenge_page.dart
https://nftprojectsboosty.atlassian.net/browse/SAT-426 Display received reward on challenge screen
=> Sat-426 Display received reward on challenge screen

lib/controller/create_account_controller.dart, lib/controller/mixin/non_working_feature_mixin.dart, lib/controller/profile_controller.dart, lib/controller/quiz_controller.dart, lib/controller/show_episode_quiz_controller.dart, lib/controller/transaction_preview_controller.dart, lib/controller/wallet_stake_controller.dart, lib/data/repository/satar_repository_impl.dart, lib/translation/en.dart, lib/ui/dialog_widget/default_dialog.dart, lib/ui/page_widget/transaction_preview_page.dart
https://nftprojectsboosty.atlassian.net/browse/SAT-396 Add snackbar after successful registration
https://nftprojectsboosty.atlassian.net/browse/SAT-211 Improve default dialog - add secondary button
https://nftprojectsboosty.atlassian.net/browse/SAT-423 Add loader to send tokens screen (preview)
=> Sat-396 Registration toast

lib/controller/password_recovery_controller.dart, lib/controller/quiz_question_controller.dart, lib/ui/page_widget/forgot_password_verification_page.dart
https://nftprojectsboosty.atlassian.net/browse/SAT-429 Duplicating API requests on Forgot password flow - special scenario
=> Sat-426 Dublicating request

lib/controller/quiz_question_controller.dart, lib/ui/page_widget/chat_page.dart, lib/ui/page_widget/home_page.dart, lib/ui/page_widget/qr_result_show_page.dart, lib/ui/page_widget/show_detail_with_episodes_page.dart, lib/ui/page_widget/show_episodes_realm_page.dart, lib/ui/page_widget/shows_category_page.dart, lib/ui/page_widget/write_review_page.dart, pubspec.lock, pubspec.yaml
https://nftprojectsboosty.atlassian.net/browse/SAT-433 Add cache for shows & episodes cover images
=> Sat-433 Image cache

lib/controller/mixin/non_working_feature_mixin.dart, lib/controller/personal_profile_controller.dart, lib/controller/show_detail_with_episodes_controller.dart, lib/data/model/show_detail_model.dart, lib/domain/entities/show_detail.dart, lib/translation/en.dart, lib/ui/page_widget/nfts_page.dart, lib/ui/page_widget/profile_page.dart, lib/ui/page_widget/show_detail_with_episodes_page.dart
https://nftprojectsboosty.atlassian.net/browse/SAT-441 Change text in the “coming soon” pop-up
https://nftprojectsboosty.atlassian.net/browse/SAT-364 Add pop-ups for non-working features
https://nftprojectsboosty.atlassian.net/browse/SAT-437 Take title and subtitle on the show screen from the API
https://nftprojectsboosty.atlassian.net/browse/SAT-438 Add link for icon “watch” on the show screen or hide it if the watch property is empty
=> Uncoming features, watch show feature

lib/data/model/payload/payload_user_model.dart, lib/domain/entities/payload/payload_user.dart, lib/ui/page_widget/quiz_lobby_page.dart
Sat-459 Wrong avatar on the quiz lobby screen
=> Sat-459 Wrong avatar on the quiz lobby screen

lib/data/datasource/impl/ApiDataSourceImpl.dart, pubspec.lock, pubspec.yaml
https://nftprojectsboosty.atlassian.net/browse/SAT-571
=> SAT-571 Add firebase device id into each API request headers

lib/controller/quiz_controller.dart, lib/data/datasource/impl/ApiDataSourceImpl.dart, lib/data/model/payload/payload_challenge_result_model.dart, lib/data/model/payload/payload_player_model.dart, lib/domain/entities/payload/payload_challenge_result.dart, lib/domain/entities/payload/payload_player.dart, lib/translation/en.dart, lib/ui/bottom_sheet_widget/quiz_winner_bottom_sheet.dart, lib/ui/page_widget/home_page.dart, lib/ui/page_widget/quiz_result_page.dart, lib/ui/theme/sator_color.dart
https://nftprojectsboosty.atlassian.net/browse/SAT-559 NATS client implemetation
https://nftprojectsboosty.atlassian.net/browse/SAT-670 Add share button to the quiz lobby
=> SAT-559 NATS client implemetation

lib/controller/quiz_controller.dart, lib/controller/quiz_result_controller.dart, lib/ui/bottom_sheet_widget/quiz_winner_bottom_sheet.dart, lib/ui/page_widget/quiz_result_page.dart, pubspec.lock, pubspec.yaml
https://nftprojectsboosty.atlassian.net/browse/SAT-712
=> SAT-712 Add animation for quiz winners

lib/controller/challenges_controller.dart, lib/controller/quiz_controller.dart, lib/ui/page_widget/challenges_page.dart
https://nftprojectsboosty.atlassian.net/browse/SAT-735
=> SAT-735 Quizzes list should be updated after each quiz

lib/controller/login_controller.dart, lib/data/repository/satar_repository_impl.dart
https://nftprojectsboosty.atlassian.net/browse/SAT-797
=> SAT-797 Endless Face ID check

lib/binding/app_binding.dart, lib/binding/rss_item_binding.dart, lib/binding/rss_list_binding.dart, lib/controller/home_controller.dart, lib/controller/rss_item_controller.dart, lib/controller/rss_list_controller.dart, lib/data/datasource/feed_data_source.dart, lib/data/datasource/impl/LocalDataSourceImpl.dart, lib/data/datasource/impl/feed_data_source_impl.dart, lib/data/datasource/local_data_source.dart, lib/data/db_adapter/adapter_type_ids.dart, lib/data/db_adapter/rss_item_adapter.dart, lib/data/repository/satar_repository_impl.dart, lib/domain/repositories/sator_repository.dart, lib/translation/en.dart, lib/ui/page_widget/home_page.dart, lib/ui/page_widget/rss_item_page.dart, lib/ui/page_widget/rss_list_page.dart, lib/ui/widget/title_button.dart, lib/util/extension.dart, pubspec.lock, pubspec.yaml
* Implement parser of the Sator medium blog feed
* tmp
* add feed item storing
* add check time for rss feed fetching
* add rss item page
* update webview package version
* remove unused
* tmp
* add rss list page
* add blog button to home
* blog feed update
* change rss item list
* rss blog on home page
* rss blog on home page
* change rss item in list
* change rss item in list, attempt 2
Co-authored-by: Michael Yemets <mgyemets@gmail.com>
=> SAT-713 Blog Feed (#242)

lib/controller/challenge_controller.dart, lib/controller/login_controller.dart, lib/controller/mixin/non_working_feature_mixin.dart, lib/controller/quiz_controller.dart, lib/controller/show_episode_quiz_controller.dart, lib/controller/show_episode_realm_controller.dart, lib/controller/splash_controller.dart, lib/controller/wallet_stake_controller.dart, lib/data/connectivity/connectivity_service.dart, lib/data/repository/satar_repository_impl.dart, lib/ui/bottom_sheet_widget/rate_bottom_sheet.dart, lib/util/getx_extension.dart, lib/util/onboarding_list.dart
https://nftprojectsboosty.atlassian.net/browse/SAT-834 Minor UI fixes
=> SAT-834 Minor UI fixes

lib/binding/app_binding.dart, lib/controller/challenge_controller.dart, lib/controller/mixin/connectivity_mixin.dart, lib/controller/mixin/validation_mixin.dart, lib/controller/nft_item_controller.dart, lib/controller/show_episode_realm_controller.dart, lib/data/connectivity/connectivity_service.dart, lib/data/connectivity/internet_connectivity.dart, lib/ui/bottom_sheet_widget/episode_realm_bottom_sheet.dart, lib/ui/bottom_sheet_widget/realm_expiring_bottom_sheet.dart, lib/ui/bottom_sheet_widget/realm_paid_activation_bottom_sheet.dart, lib/ui/page_widget/nft_item_page.dart, lib/ui/page_widget/show_episodes_realm_page.dart
https://nftprojectsboosty.atlassian.net/browse/SAT-836 Disable paid features without internet
=> SAT-836 Disable paid features without internet

lib/ui/page_widget/active_realms_page.dart, lib/ui/page_widget/nfts_categories_page.dart, lib/ui/page_widget/reviews_page.dart, lib/ui/page_widget/settings_about_page.dart, lib/ui/page_widget/settings_change_info_page.dart, lib/ui/page_widget/settings_page.dart, lib/ui/theme/light_theme.dart
https://nftprojectsboosty.atlassian.net/browse/SAT-843 Fix background size on IPad
=> SAT-843 Fix background size on IPad

lib/ui/page_widget/nft_item_page.dart
https://nftprojectsboosty.atlassian.net/browse/SAT-839 NFT description is not scrollable
=> SAT-839 NFT description is not scrollable

lib/controller/write_review_controller.dart, lib/translation/en.dart, lib/ui/page_widget/write_review_page.dart, lib/ui/widget/input_text_field.dart
https://nftprojectsboosty.atlassian.net/browse/SAT-846 Set up min characters for the episode review
=> SAT-846 Set up min characters for the episode review

lib/controller/create_account_controller.dart, lib/controller/email_verification_controller.dart, lib/controller/login_controller.dart, lib/controller/settings_change_info_controller.dart, lib/controller/splash_controller.dart, lib/translation/en.dart, lib/ui/page_widget/email_verification_page.dart
https://nftprojectsboosty.atlassian.net/browse/SAT-742 Figure out how to clear token (logout) on the Verification code screen
=> SAT-742 Add possibility to 'logout' on verification page

lib/controller/home_controller.dart, lib/controller/rss_list_controller.dart
https://nftprojectsboosty.atlassian.net/browse/SAT-873 Sort blog posts by creation date in reverse order
=> SAT-873 Sort blog posts by creation date in reverse order

lib/controller/home_controller.dart, lib/controller/quiz_controller.dart, lib/controller/quiz_result_controller.dart, lib/controller/show_episode_realm_controller.dart, lib/data/datasource/firebase_data_source.dart, lib/data/datasource/impl/FirebaseDataSourceImpl.dart, lib/data/repository/satar_repository_impl.dart, lib/domain/repositories/sator_repository.dart, lib/translation/en.dart, lib/ui/bottom_sheet_widget/success_answer_bottom_sheet.dart, lib/ui/page_widget/home_page.dart, lib/ui/page_widget/quiz_result_page.dart, lib/ui/page_widget/show_episodes_realm_page.dart
https://nftprojectsboosty.atlassian.net/browse/SAT-875 Required changes for the app store
=> SAT-875 Required changes for the app store

lib/controller/challenge_controller.dart, lib/controller/challenges_controller.dart, lib/controller/quiz_result_controller.dart, lib/ui/page_widget/challenge_page.dart, lib/ui/page_widget/challenges_page.dart
https://nftprojectsboosty.atlassian.net/browse/SAT-875
=> Sat-875 Another appstore changes

lib/controller/show_episode_realm_controller.dart
https://nftprojectsboosty.atlassian.net/browse/SAT-885 Ignore empty puzzle unlock options list (for all OS)
=> SAT-885 Ignore empty puzzle unlock options list (for all OS)

lib/controller/home_controller.dart, lib/data/datasource/api_data_source.dart, lib/data/datasource/impl/ApiDataSourceImpl.dart, lib/data/datasource/impl/LocalDataSourceImpl.dart, lib/data/datasource/local_data_source.dart, lib/data/db_adapter/adapter_type_ids.dart, lib/data/db_adapter/sao_wallet_adapter.dart, lib/data/model/sao_wallet_config_model.dart, lib/data/repository/satar_repository_impl.dart, lib/domain/entities/sao_wallet.dart, lib/domain/entities/sao_wallet_config.dart, lib/domain/repositories/sator_repository.dart, lib/ui/page_widget/home_page.dart
https://nftprojectsboosty.atlassian.net/browse/SAT-872 Show previous balance value or 0, until it's updated
=> SAT-872 Show previous balance value or 0, until it's updated

lib/controller/puzzle_controller.dart, lib/data/model/puzzle/puzzle_game_model.dart, lib/domain/entities/puzzle/puzzle_game.dart, lib/translation/en.dart, lib/ui/page_widget/puzzle_page.dart
https://nftprojectsboosty.atlassian.net/browse/SAT-888 Show only taken steps and hide rewards line if `is_rewards_disabled=true`
=> SAT-888 Show only taken steps and hide rewards line
